name: Test Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  
  strategy:
    matrix:
      node-version: [12.4]

  steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: 'Print dir'
      run: pwd
    - name: 'List files'
      run: ls -la
    - name: 'First action passes'
      uses: ./.github/actions/passing-action
    - name: 'This should fail'
      uses: ./.github/actions/failing-action
    - name: 'This should not run'
      uses: ./.github/actions/unrun-action
